version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: yuuki070951
      POSTGRES_USER: s_yuki0709
      POSTGRES_DB: recordcrew_development
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/myapp"
    environment:
      POSTGRES_PASSWORD: yuuki070951
      POSTGRES_USER: s_yuki0709
      POSTGRES_DB: recordcrew_development
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres-data: